server:
  port: 8761 # ??
spring:
  application:
    name: eureka-server # ???????Eureka???
eureka:
  client:
    register-with-eureka: false # ??????????EurekaServer????true
    fetch-registry: false # ???????????????true
    service-url: # EurekaServer?????????????????????????Server????
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  instance:
    hostname: eureka-server